import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gsap } from "gsap";
import { useEffect, useState } from "react";
import Services from "../components/Services";
import Project from "../components/Project";
import Contact from "../components/Contact";

export default function Home() {
  const [services, setServices] = useState(false);
  const [projet, setProjet] = useState(false);
  const [contact, setContact] = useState(false);
  const [about, setAbout] = useState(false);

  useEffect(() => {
    gsap.fromTo(
      "#gsap",
      {
        opacity: 0,
      },
      {
        opacity: 1,
        stagger: 0.5,
      }
    );
 
  }, []);

  const text = "Romain Marty Développeur Web";

  const text2 = () => {
    // create span for each letter
    const letters = text.split("").map((letter, index) => {
      return (
        <span key={index} id="gsap" className={styles.letter}>
          {letter}
        </span>
      );
    });
    return letters;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="box">
          <div className="boxCenterY">
            <h1>{text2()}</h1>
          </div>
          <img src="./asset/image1.png" alt="" />
        </div>
        <div className="box2">
          <h2>"Faison grandir nos projet ensemble"</h2>
        </div>
      </header>
      <main className="middle">
        <div className="box3">
          <div className="navBar">
            <ul>
              <li>
                <a
                  href="#"
                  onClick={() => {
                    setServices(!services);
                    setProjet(false);
                    setContact(false);
                    setAbout(false);
                  }}
                >
                  Mes services
                </a>
              </li>
              <li>
                <a
                  href="#"
                  onClick={() => {
                    setProjet(!projet);
                    setServices(false);
                    setContact(false);
                    setAbout(false);
                  }}
                >
                  Mes projets
                </a>
              </li>
              <li>
                <a
                  href="#"
                  onClick={() => {
                    setContact(!contact);
                    setServices(false);
                    setProjet(false);
                    setAbout(false);
                  }}
                >
                  Contact
                </a>
              </li>
              <li>
                <a
                  href="#"
                  onClick={() => {
                    setAbout(!about);
                    setServices(false);
                    setProjet(false);
                    setContact(false);
                  }}
                >
                  Qui suis-je?
                </a>
              </li>
            </ul>
          </div>
        </div>
      </main>
      <main>
        {services ? <Services /> : null}
        {projet ? <Project /> : null}
        {contact ? <Contact /> : null}
      </main>
      <footer className="footer">
        <div className="box4">Je suis le footer</div>
      
      </footer>
    </>
  );
}
